name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install SSHpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy changes
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -l root -p 22 ${{ secrets.SERVER_IP }} 'cd /home/brocode-server/ && git pull origin main && docker-compose down && docker-compose up -d'
